# Generated by Django 5.2.5 on 2025-09-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='src_url',
        ),
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
