# Generated by Django 5.2.5 on 2025-09-03 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_media_src_url_media_file_alter_product_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='file',
            new_name='image',
        ),
    ]
